#!/bin/bash

## Runs our custom minmaxer to produce the right format for the data
if [ ! -e regular.tri ]
then 
    echo "Running minmaxer..."
    echo "9 0" | ./minmaxer/source.minmaxer/minmaxer finalData/hw4.heights >/dev/null
    rm regular.edges
    echo "done"
fi

## Then calls our tour executable giving the data
./tour 10 regular.tri finalData/hw4.tour
